name: Run linter

on:
  pull_request:
    branches: [master, dev]

jobs:
  flake8:
    name: Run flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install .[dev]
      - name: Lint with flake8
        run: flake8