name: Upload Python Package to TestPyPi

on:
  push:
    branches: [master, dev, pypi_automation]

jobs:

  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: >-
      Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/kegg-pathways-completeness
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Check if package version exists on TestPyPI
        run: |
          PACKAGE_NAME=<your-package-name>
          VERSION=$(python setup.py --version)
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://test.pypi.org/pypi/${PACKAGE_NAME}/${VERSION}/json)
          if [ $RESPONSE -eq 200 ]; then
            echo "Package version already exists on TestPyPI."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Package version does not exist on TestPyPI."
            echo "exists=false" >> $GITHUB_ENV
          fi
      - name: Download all the dists
        if: env.exists == 'false'
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        if: env.exists == 'false'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/